import { useLocation, useNavigate } from "react-router-dom";
import { useState, useEffect } from "react";
import { ArrowLeft, Sparkles, RefreshCw, Filter, Heart, FileText, ShoppingBag, Loader2, Crown, Lock } from "lucide-react";
import { Button } from "@/components/ui/button";
import BackButton from "@/components/BackButton";
import OutfitCard from "@/components/OutfitCard";
import { UserProfile, OutfitRecommendation } from "@/types/outfit";
import { StyleReport, PhotoAnalysisResult } from "@/types/styleReport";
import StyleReportCard from "@/components/StyleReport/StyleReportCard";
import OccasionSection from "@/components/StyleReport/OccasionSection";
import ReportGeneratingScreen from "@/components/StyleReport/ReportGeneratingScreen";
import { useStyleReport } from "@/hooks/useStyleReport";
import { useProductSearch } from "@/hooks/useProductSearch";
import { occasionCategories, getOccasionOutfits } from "@/data/occasionOutfits";
import { Progress } from "@/components/ui/progress";
import { usePremium } from "@/hooks/usePremium";
import DesktopBackground from "@/components/DesktopBackground";

const Recommendations = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const profile = location.state?.profile as UserProfile | undefined;
  const photoAnalysisFromWizard = location.state?.photoAnalysis as PhotoAnalysisResult | undefined;
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState<StyleReport | null>(null);
  const [activeTab, setActiveTab] = useState<"outfits" | "report" | "occasions">("outfits");
  const [searchProgress, setSearchProgress] = useState(0);
  const [searchStage, setSearchStage] = useState("");

  const { generateReport, isLoading } = useStyleReport();
  const { outfits: aiOutfits, isSearching, searchProducts } = useProductSearch();
  const { isPremium, canGenerate, generationCount, recordGeneration, loading: premiumLoading } = usePremium();

  // Auto-generate on mount
  const [autoGenerated, setAutoGenerated] = useState(false);

  useEffect(() => {
    if (profile && !autoGenerated && !generatedReport && !premiumLoading && canGenerate) {
      setAutoGenerated(true);
      handleGenerateReport();
    }
  }, [profile, premiumLoading, canGenerate]);

  // Progress animation during search
  useEffect(() => {
    if (isSearching) {
      setSearchProgress(0);
      setSearchStage("🔍 Searching Indian e-commerce stores...");
      const stages = [
        { progress: 15, stage: "🔍 Searching Myntra, Ajio, Amazon..." },
        { progress: 35, stage: "🛍️ Finding best deals within your budget..." },
        { progress: 55, stage: "✨ Matching products to your style profile..." },
        { progress: 75, stage: "💰 Comparing prices across stores..." },
        { progress: 90, stage: "📦 Curating your perfect outfits..." },
      ];
      let i = 0;
      const interval = setInterval(() => {
        if (i < stages.length) {
          setSearchProgress(stages[i].progress);
          setSearchStage(stages[i].stage);
          i++;
        }
      }, 3000);
      return () => clearInterval(interval);
    } else {
      setSearchProgress(100);
      setSearchStage("");
    }
  }, [isSearching]);

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: "INR",
      maximumFractionDigits: 0,
    }).format(value);
  };

  const handleGenerateReport = async () => {
    if (!profile) return;
    if (!canGenerate) return;
    await recordGeneration();
    setIsGenerating(true);
  };

  const handleReportComplete = async () => {
    if (!profile) {
      setIsGenerating(false);
      return;
    }
    const report = await generateReport(profile, photoAnalysisFromWizard);
    if (report) {
      setGeneratedReport(report);
      // Persist to DB and localStorage
      try {
        const { supabase: sb } = await import("@/integrations/supabase/client");
        const { data: userData } = await sb.auth.getUser();
        if (userData?.user) {
          await sb.from("style_reports").insert({
            user_id: userData.user.id,
            report_data: report as any,
            quiz_inputs: profile ? { gender: profile.gender, bodyType: profile.bodyType, occasion: profile.occasion } as any : null,
          });
        }
        localStorage.setItem("luxfit-last-report", JSON.stringify(report));
      } catch {}
      setIsGenerating(false);

      // Immediately search for real products using the report
      setSearchStage("🔍 Searching for real products...");
      await searchProducts(
        report,
        profile.budgetMin,
        profile.budgetMax,
        profile.gender,
        profile.occasion,
        profile.season,
      );
      setActiveTab("outfits");
    } else {
      setIsGenerating(false);
    }
  };

  const handleRetrySearch = async () => {
    if (!generatedReport || !profile) return;
    await searchProducts(
      generatedReport,
      profile.budgetMin,
      profile.budgetMax,
      profile.gender,
      profile.occasion,
      profile.season,
    );
  };

  const getOccasionLabel = (occasion: string) => {
    const labels: Record<string, string> = {
      wedding: "Wedding",
      diwali: "Diwali",
      office: "Office",
      "date-night": "Date Night",
      party: "Party",
      casual: "Casual",
      formal: "Formal Event",
      christmas: "Christmas",
    };
    return labels[occasion] || occasion;
  };

  const getSeasonLabel = (season: string) => {
    const labels: Record<string, string> = {
      summer: "Summer",
      winter: "Winter",
      monsoon: "Monsoon",
      spring: "Spring",
    };
    return labels[season] || season;
  };

  // Show generation limit reached screen for free users
  if (!premiumLoading && !canGenerate && !generatedReport && !isGenerating) {
    return (
      <div className="min-h-screen bg-background relative">
        <div className="absolute top-4 left-4 z-20">
          <BackButton to="/" label="Back to Home" />
        </div>
        <div className="min-h-screen flex items-center justify-center">
        <div className="text-center max-w-md mx-auto px-6">
          <div className="w-20 h-20 mx-auto mb-6 rounded-2xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center border border-primary/20">
            <Lock className="w-10 h-10 text-primary" />
          </div>
          <h2 className="font-serif text-3xl text-foreground mb-3">Generation Limit Reached</h2>
          <p className="text-muted-foreground mb-2">
            You've used all <strong>2 free</strong> outfit generations.
          </p>
          <p className="text-muted-foreground mb-8 text-sm">
            Upgrade to Premium for <strong>unlimited</strong> outfit generations, virtual closet access, and more.
          </p>
          <div className="flex flex-col gap-3">
            <Button variant="luxury" size="lg" onClick={() => navigate('/profile')}>
              <Crown className="w-5 h-5 mr-2" />
              Upgrade to Premium
            </Button>
            <Button variant="ghost" onClick={() => navigate('/')}>
              Back to Home
            </Button>
          </div>
        </div>
        </div>
      </div>
    );
  }

  if (isGenerating) {
    return <ReportGeneratingScreen onComplete={handleReportComplete} duration={10} />;
  }

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 bg-background/80 backdrop-blur-md border-b border-border/50">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <button
            onClick={() => navigate("/get-outfit")}
            className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
            <span className="hidden sm:inline">Modify Preferences</span>
          </button>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary to-gold-dark flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-primary-foreground" />
            </div>
            <span className="font-serif text-lg">Aurion AI</span>
          </div>
          <Button variant="ghost" size="icon">
            <Filter className="w-5 h-5" />
          </Button>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 md:py-12">
        <div className="text-center mb-8 animate-fade-up">
          <div className="inline-flex items-center gap-2 bg-primary/10 px-4 py-2 rounded-full text-primary text-sm font-medium mb-6">
            <Sparkles className="w-4 h-4" />AI-Curated Just For You
          </div>
          <h1 className="font-serif text-4xl md:text-5xl lg:text-6xl text-foreground mb-4">
            Your Perfect <span className="text-gradient-gold">Style</span>
          </h1>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto mb-6">
            Real products from Indian stores within your budget of{" "}
            {formatCurrency(profile?.budgetMin || 5000)} – {formatCurrency(profile?.budgetMax || 25000)}
          </p>
          {profile && (
            <div className="flex flex-wrap justify-center gap-2 mt-4">
              {profile.gender && (
                <span className="px-4 py-2 rounded-full bg-secondary text-sm text-foreground capitalize flex items-center gap-2">
                  <Heart className="w-3 h-3 text-primary" />
                  {profile.gender === "female" ? "Women's" : "Men's"} Fashion
                </span>
              )}
              {profile.occasion && (
                <span className="px-4 py-2 rounded-full bg-secondary text-sm text-foreground">
                  {getOccasionLabel(profile.occasion)}
                </span>
              )}
              {profile.season && (
                <span className="px-4 py-2 rounded-full bg-secondary text-sm text-foreground">
                  {getSeasonLabel(profile.season)}
                </span>
              )}
              {profile.skinTone && (
                <span className="px-4 py-2 rounded-full bg-secondary text-sm text-foreground capitalize">
                  {profile.skinTone} Skin
                </span>
              )}
            </div>
          )}
        </div>

        {/* Generation limit banner for free users */}
        {!isPremium && (
          <div className="max-w-xl mx-auto mb-8 p-4 rounded-2xl bg-primary/5 border border-primary/20 flex items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <Sparkles className="w-5 h-5 text-primary flex-shrink-0" />
              <p className="text-sm text-foreground">
                <strong>{Math.max(0, 2 - generationCount)}</strong> free generation{2 - generationCount !== 1 ? 's' : ''} remaining
              </p>
            </div>
            <Button variant="luxury" size="sm" onClick={() => navigate('/profile')} className="text-xs flex-shrink-0">
              <Crown className="w-3.5 h-3.5 mr-1" />
              Upgrade
            </Button>
          </div>
        )}

        {/* Product Search Progress */}
        {isSearching && (
          <div className="max-w-xl mx-auto mb-10 p-6 rounded-2xl bg-card border border-border/50">
            <div className="flex items-center gap-3 mb-4">
              <Loader2 className="w-5 h-5 text-primary animate-spin" />
              <p className="text-foreground font-medium">{searchStage}</p>
            </div>
            <Progress value={searchProgress} className="h-2" />
            <p className="text-xs text-muted-foreground mt-2 text-center">
              Finding real products across Myntra, Ajio, Amazon, Flipkart & more
            </p>
          </div>
        )}

        {/* Tabs */}
        <div className="flex justify-center gap-2 mb-8 flex-wrap">
          <Button
            variant={activeTab === "outfits" ? "luxury" : "luxuryOutline"}
            onClick={() => setActiveTab("outfits")}
            className="gap-2"
          >
            <ShoppingBag className="w-4 h-4" />
            Outfits {aiOutfits.length > 0 && `(${aiOutfits.length})`}
          </Button>
          {generatedReport && (
            <Button
              variant={activeTab === "report" ? "luxury" : "luxuryOutline"}
              onClick={() => setActiveTab("report")}
              className="gap-2"
            >
              <FileText className="w-4 h-4" />
              Style Report
            </Button>
          )}
          <Button
            variant={activeTab === "occasions" ? "luxury" : "luxuryOutline"}
            onClick={() => setActiveTab("occasions")}
            className="gap-2"
          >
            <Heart className="w-4 h-4" />
            Shop by Occasion
          </Button>
        </div>

        {activeTab === "outfits" && (
          <div className="space-y-6 max-w-5xl mx-auto">
            {aiOutfits.length > 0 ? (
              <>
                {aiOutfits.map((outfit, index) => (
                  <OutfitCard key={outfit.id} outfit={outfit} index={index} />
                ))}
                <div className="text-center mt-12">
                  <Button
                    variant="luxuryOutline"
                    size="lg"
                    onClick={handleRetrySearch}
                    disabled={isSearching}
                  >
                    <RefreshCw className={`w-5 h-5 mr-2 ${isSearching ? "animate-spin" : ""}`} />
                    Search Again
                  </Button>
                </div>
              </>
            ) : !isSearching && !isGenerating ? (
              <div className="text-center py-16">
                <div className="w-20 h-20 mx-auto mb-6 rounded-2xl bg-primary/10 flex items-center justify-center">
                  <Sparkles className="w-10 h-10 text-primary" />
                </div>
                <h3 className="font-serif text-2xl text-foreground mb-2">
                  {generatedReport ? "No Products Found" : "Generating Your Style Profile..."}
                </h3>
                <p className="text-muted-foreground mb-6">
                  {generatedReport
                    ? "We couldn't find products in your budget. Try adjusting your preferences."
                    : "Our AI stylist is analyzing your profile and searching for real products."}
                </p>
                {generatedReport && (
                  <div className="flex flex-wrap justify-center gap-3">
                    <Button variant="luxury" onClick={handleRetrySearch}>
                      <RefreshCw className="w-5 h-5 mr-2" />
                      Try Again
                    </Button>
                    <Button variant="luxuryOutline" onClick={() => navigate("/get-outfit")}>
                      Adjust Preferences
                    </Button>
                  </div>
                )}
              </div>
            ) : null}
          </div>
        )}

        {activeTab === "report" && generatedReport && (
          <div className="max-w-4xl mx-auto">
            <StyleReportCard report={generatedReport} />
          </div>
        )}

        {activeTab === "occasions" && (
          <div className="max-w-5xl mx-auto">
            {occasionCategories.map((category) => (
              <OccasionSection
                key={category.id}
                title={category.title}
                subtitle={category.subtitle}
                icon={category.icon}
                outfits={getOccasionOutfits(profile?.gender || "male", category.id)}
                stylingTip={category.stylingTip}
              />
            ))}
          </div>
        )}
      </main>

      <footer className="border-t border-border/50 mt-16 py-8">
        <div className="container mx-auto px-4 text-center">
          <div className="flex items-center justify-center gap-2 mb-4">
            <Sparkles className="w-5 h-5 text-primary" />
            <span className="font-serif text-xl">Aurion AI</span>
          </div>
          <p className="text-sm text-muted-foreground">Your Personal AI Style Curator</p>
        </div>
      </footer>
    </div>
  );
};

export default Recommendations;
